# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r:
  - oldrel
  - release
  - devel
sudo: false
cache: packages

r_github_packages:
  - jimhester/covr

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes"

after_success:
  - Rscript -e 'covr::codecov()'
